/* global  _appConstant */

module.exports = {
    ACCESS_DENIED: 'Access denied',
    NO_AUTH: 'Not Authorised',
    NO_AUTH_TO_ACCESS_PROFILE: 'You are not authorized to access this profile. You may ask your trusted contact to introduce you to this person.',

    LOGIN_WITH_EMAIL_FIRST: 'oops! You have to login once via email password to enable Bio metric login.',
    CONVO_CANT_INITIATE: 'Cannot initiate conversations',
    PUBLICATION_DELETED: 'This publication has been deleted by the owner',
    INVITE_SENT_VIA_EMAIL: 'Invitation sent via email',

    ACCOUNT_BLOCKED: 'Account is blocked',
    USER_ALREADY_BLOCKED: 'User is alreday Blocked',
    USER_NOT_BLOCKED: 'User is not blocked',

    POST_NOT_FOUND: 'Post not found',
    SELF_AWARD_ERROR: 'Self award are not allowed',

    REQUIRED_EMAIL: 'Email is required',
    REQUIRED_UUID: 'Uuid is required',
    REQUIRED_OTP: 'OTP is required',
    REQUIRED_PASSWORD: 'Password is required',
    REQUIRED_MESSAGE: 'Message is required',
    REQUIRED_APPROVER_USER_ID: 'Approver User Id is required',
    REQUIRED_CONTRIBUTION_TXT: 'Contribution text is required',
    REQUIRED_RECIEVERS: 'Conversation members are required',
    CONVERSATION_MIN_RECEIVER: 'At least 2 user are required for group  conversation',
    REQUIRED_DURATION: 'Duration is required',
    REQUIRED_A_RECIEVER: 'A member is required',
    REQUIRED_USER_IDS: 'user ids are required',
    REQUIRED_USER_ID: 'user id is required',
    REQUIRED_AWARD_ID: 'Award id is required',
    REQUIRED_TEXT: 'Text is required',
    REQUIRED_FILE: 'File is required',
    REQUIRED_FILE_TYPE: 'File type is required',
    REQUIRED_PROFILE_ID: 'Profile id is required',
    REQUIRED_REFERRAL_CODE: 'An invite code is required.',
    REQUIRED_URL: 'url is required',
    REQUIRED_TYPE_ID: 'Type id is required',
    EMPTY_NAME: 'Name cannot be empty',
    REQUIRED_POST_TITLE: 'Title is required',

    INVALID_CREDENTIALS: 'Invalid Credentials',
    INVALID_OTP: 'Invalid OTP',
    INVALID_EMAIL_ID: 'Invalid email id',
    INVALID_CONTRIBUTION_ID: 'invalid contribution id',
    INVALID_FRIENDS: 'Invalid friends',
    INVALID_REFERRAL_CODE: 'Invalid invite code',
    INVALID_TYPE: 'Type is invalid',
    DEVICE_TYPE_REQUIRED_OR_INVALID: 'Device type is required or invalid',
    DEVICE_TOKEN_REQUIRED_OR_INVALID: 'Device token is required or invalid',

    NO_ACCOUNT: 'This account does not exist',
    NO_USER: 'User does not exist',
    NO_OTP: 'OTP does not exists',
    NO_PUBLICATION: 'Publication not found',
    NO_CONTRIBUTION: 'Contribution not found',
    NO_REQUEST: 'Request not found',
    NO_GROUP: 'Group not found',
    NO_MESSAGE: 'Message not found',
    NO_INVITATION: 'Invitation not found',
    NO_REFERRAL: 'No invite code found',
    NO_IMAGE: 'Image not found',
    NO_FRIEND: 'Friend not found',
    NO_USER_ANALYTIC: 'No alytics stored for user',
    NO_INVITER: 'Inviter account does not exist',

    USER_ALREADY_EXIST: 'User already exist',
    REQUEST_PENDING_FOR_APPROVAL: 'Request is pending for approval',
    REQUEST_ALREADY_APPROVED: 'Request already approved',
    REQUEST_ALREADY_REJECTED: 'Request already rejected',
    INVITATION_ALREADY_SENT: 'Invitation is already sent',
    INVITATION_ALREADY_REJECTED: 'Invitation already rejected',
    INVITATION_ALREADY_ACCEPTED: 'Invitation already accepted',
    INVITATION_PENDING: 'Invitation already pending for this user.',
    EMAIL_ALREADY_EXIST: 'Email already exist',
    EMAIL_ALREADY_ADDED: 'Email already added',
    SELF_INVITE_SEND: 'Cannot send invite to yourself',
    SELF_INVITE_ACCEPT: 'Cannot accept self invitation',

    ONLY_FRIENDS_IN_GROUP: 'Only friend are added in a group',
    ONLY_ADMIN_DELETE_GROUP: 'Only Admin can delete group',

    FRIEND_LIST_FULL: 'Your featured list is currently full. Please unfeature one trusted contact in order to feature this one.',
    MAX_FRIEND_LIMIT: 'You can only make ' + _appConstant.MAX_FRIENDS + ' connections',
    ALREADY_CONTACT: 'Already a trusted contact',

    NOT_ENOUGH_COINS: 'Sorry, you don\'t have enough coins',
    ALREADY_MARKED: 'This contribution is aready marked as best',

    REFERRAL_EXPIRED: 'This referral code is already expired',
    REFERRAL_ALREADY_USED: 'This referral code is already used',
    REFERRAL_ALREADY_REJECTED: 'This referral code is already rejected',

    USER_BLOCKED_BY_YOU: 'You have blocked this user. Please unblock first.',
    UNAUTH_PROFILE_BLOCKED_BY_USER: 'You are not authorized to access this profile. You are blocked by this user.',
    BLOCKED_BY_USER: 'Cannot perform action. You are blocked by this user.',
    RECOMMEND_FAILED_USER_BLOCKED: 'Cannot recommend this user. This user has been blocked by you.',
    RECOMMEND_FAILED_BLOCKED_BY_USER: 'Cannot recommend this user. You are blocked by this recommended user.'
};